language: node_js
node_js:
   - 0.6


env: DB=couchdb

before_script:
  - curl -X PUT localhost:5984/myapp_test
  - npm install kanso -g
  - npm install nodeunit -g


script: "kanso install; kanso push http://localhost:5984/myapp_test"

after_script:
  # setup and run tests
  - sh -e /etc/init.d/xvfb start
  # need to setup couch with some stuff
  - curl -X PUT http://localhost:5984/_config/httpd/secure_rewrites -H 'Content-Type: application/json' -d 'false'
  - "export DISPLAY=:99.0; test/run_headless_tests.sh http://localhost:5984/myapp_test"


notifications:
  email:
    - ryan.ramage@gmail.com
